site_name: Judy Curie
repo_name: judycurie/jmc
site_url: https://www.judycurie.com/
copyright: Judy Curie

nav:
    - ...: index.md
    - Science:
      - nav/science/research.md
      - nav/science/publications.md
      - nav/science/teaching.md
      
    - Is:
      - nav/is/about.md
      - nav/is/cv.md
    - Art:
      - nav/art/projects.md
      - nav/art/nft.md



theme:
  name: simple-blog
  title_style: normal
  favicon: assets/logo.svg
  logo: assets/logo.svg
  # theme_style: light
  colors:
    text: black
    title: black
    primary: black
    background: white
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
